Document: gocrypto
Title: Debian gocrypto Manual
Author: <insert document author here>
Abstract: This manual describes what gocrypto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gocrypto/gocrypto.sgml.gz

Format: postscript
Files: /usr/share/doc/gocrypto/gocrypto.ps.gz

Format: text
Files: /usr/share/doc/gocrypto/gocrypto.text.gz

Format: HTML
Index: /usr/share/doc/gocrypto/html/index.html
Files: /usr/share/doc/gocrypto/html/*.html
